### ISSUE TITLE
Modification so that "analyze" works for complex-valued signal

### ISSUE THREAD

**Issue by jane2L** [baggepinnen/SingularSpectrumAnalysis.jl#16]
Hello, thanks for the great work on this package! 
I am working with complex valued time series and I noticed that using the analyse function with a complex-valued signal yields an "Inexact" error which comes from the reconstruct function. I think a simple way to make the method adapted to both real and complex valued signals would be to replace the line 101 of your code in the reconstruct function: 

"  yr = zeros(N,M)"
could be changed for
" yr = Array{Complex{Float64}}(undef,N,M)" 

Cheers,
Jeanne.

**Comment by baggepinnen** [comment]
Hey and thanks for the report Jeanne!
I pushed https://github.com/baggepinnen/SingularSpectrumAnalysis.jl/commit/ecca24e80018940b1af8a1bbab6b43d635c44cd2
which should hopefully solve your problem. Feel free to 
```julia
pkg> add SingularSpectrumAnalysis#master
```
and see if it works. If it does, I'll tag a new release :)

**Comment by jane2L** [comment]
I just tested it and it works :). Thanks!

**Comment by baggepinnen** [comment]
Great, thanks :)
