### ISSUE TITLE
ERROR: OutOfMemoryError()

### ISSUE THREAD

**Issue by StefanPofahl** [baggepinnen/SingularSpectrumAnalysis.jl#22]
I deal with recorded data with a sampling speed above 99kHz, if a signal comprises ten periods @0.1Hz the number of points is quite huge (these big data files is the reason for Julia instead of Octave).
Now my idea was, to utilize the esprit-function to calculate the initial guess for the frequencies in a signal, unfortunately Julia v1.6.7 throws the error message above, you can reproduce this error if you generate a signal with e.g. 19999901 points :-(

**Comment by baggepinnen** [comment]
That is kind of expected if you look into how ESPRIT works, it takes an SVD of the lag-embedding matrix. You could get around this by computing a truncated SVD (using, e.g., TSVD.jl), provided that you can store the lag embedding matrix in the first place..

A much more reasonable approach is probably to downsample the data, I don't think you need 1e6 data points per period to estimate the frequency? Try `DSP.resample`. With a significantly downsampled signal, you could get a good initial frequency estimate that can be used for, e.g., gradient-based fine tuning

**Comment by StefanPofahl** [comment]
Thanks for the suggestion! This is an option, my workaround is at the moment a call of the FFT-function ...
