### ISSUE TITLE
Apple Accelerate

### ISSUE THREAD

**Issue by Roh-codeur** [baggepinnen/SingularSpectrumAnalysis.jl#24]
hi

thanks for putting this package together - this is indeed an incredible package. what are your thoughts on using Apple Accelerate? I feel it might help those of us on Macs?

https://github.com/JuliaLinearAlgebra/AppleAccelerate.jl

thanks
Roh

**Comment by baggepinnen** [comment]
The only computationally expensive part in singular spectrum analysis is an SVD, and as far as I can tell this is not included in apple accelerate? How did you intend to use AA to speed things up?

**Comment by Roh-codeur** [comment]
thanks for your response. 

I am sorry, I didnt put it together well. I meant it as a question. I am using SSA on a very big dataset and notice slowness both with the number of groups and the length of tickers I have to run this on. I was wondering if Apple Accelerate would help us, given I have heard so much of Apple M1 chips prowess.

**Comment by baggepinnen** [comment]
No apple accelerate is not the correct tool for that. The computationally expensive part is the SVD, so you could try to use a faster version of SVD instead. I don't know what apple offers here, but there are randomized SVD algorithms that are very fast, but approximative

**Comment by Roh-codeur** [comment]
got it, thanks for the response mate
