### ISSUE TITLE
[Future Plan] missing data treatment or gap filling and data forecasting

### ISSUE THREAD

**Issue by daxiawj** [baggepinnen/SingularSpectrumAnalysis.jl#3]
This package cannot deal with time series with missing data, would that be the future plan?
Also, SSA is an important methods in gap filling and data forecasting. will this be in future plan? 

As I know, there is a such package in R, which is very powerful yet the speed is not as fast as this package in Julia.

Thanks!

**Comment by baggepinnen** [comment]
Hello! 

I implemented this package simply to get familiar with SSA and have in fact not made much use of it myself. I provided the code as a Julia package for anyone to use or build upon, should they be interested. Hence, there is not really a future plan for the package at the moment. Naturally, I would be happy to accept pull requests if the package is extended by a user, but my own development of the package will probably be limited. 

Fredrik

**Comment by baggepinnen** [comment]
Forecasting has now been added, instructions are in the readme and a full runnable example in the `examples` folder.
This requires SingularSpectrumAnalysis#master.

**Comment by baggepinnen** [comment]
Gap filling should now work provided that the number of gaps is small. See keyword `robust` to functions `analyze` and `hsvd`. To indicate that there is missing data, you can set the missing entries to something very large.

See documentation here https://github.com/baggepinnen/SingularSpectrumAnalysis.jl#missing-data--outliers
