### ISSUE TITLE
Error when changing ar_order

### ISSUE THREAD

**Issue by mthelm85** [baggepinnen/SingularSpectrumAnalysis.jl#6]
When I change the ```ar_order``` argument in ```PredictionData(yt, ys, trend_order=1, ar_order=2)``` to anything more than 2, I get the following error (when using 6, for example):

```
ERROR: BoundsError: attempt to access 3-element Array{Float64,1} at index [7]
```

I’m not sure which 3-element Array it is trying to access, but it seems to always contain 3 elements, no matter what I do.

**Comment by mthelm85** [comment]
Hi there, any movement on this? Thanks!

**Comment by baggepinnen** [comment]
I can not reproduce the problem, if I change `ar_order` to 6 I get what's expected, 
```julia
pd  = PredictionData(yt, ys, trend_order=1, ar_order=6)

julia> pd.seasonal_models[1]
ControlSystems.TransferFunction{ControlSystems.SisoRational{Float64}}
                                                                          1.0
--------------------------------------------------------------------------------------------------------------------------------------------------------
1.0*z^6 - 2.4570519519269807*z^5 + 2.009238228521461*z^4 - 0.5397813438863344*z^3 + 0.24057803918898474*z^2 - 0.35382268274960516*z + 0.1473215793511019

Sample Time: 1.0 (seconds)
Discrete-time transfer function model

**Comment by baggepinnen** [comment]
If you post the full error message I can try to determine which package is at fault. Maybe I need to tag a new release of CSI or something
